require("../js/string.js");

describe("String.prototype.myConcat - Specific Examples", () => {
  test("concatenates numeric string arguments", () => {
    expect("".myConcat("1", "2", "3", "4")).toBe("1234");
  });

  test("works with spread array of strings", () => {
    const args = ["Hello", " ", "Venkat", "!"];
    expect("".myConcat(...args)).toBe("Hello Venkat!");
  });

  test("coerces an object to string representation", () => {
    expect("".myConcat({})).toBe("[object Object]");
  });

  test("coerces an empty array to an empty string", () => {
    expect("".myConcat([])).toBe("");
  });

  test('coerces null to "null"', () => {
    expect("".myConcat(null)).toBe("null");
  });

  test('coerces boolean true to "true"', () => {
    expect("".myConcat(true)).toBe("true");
  });

  test("handles arguments generated by native concat", () => {
    const nested = "abc".concat("pqr").concat("xyz");
    expect("".myConcat(nested)).toBe("abcpqrxyz");
  });

  test("handle special objects like date", () => {
    const date = new Date();
    expect("".myConcat(date).toBe);
  });

  test("coerces new Date(0) to its string representation", () => {
    const d = new Date(0);
    expect("".myConcat(d)).toBe(String(d));
  });
});
